import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'mifare_dump.dart';

/// Exports a MIFARE Classic dump to formats other tools can emulate from —
/// since the phone itself cannot emulate Classic. The phone is the reader;
/// a Flipper Zero / Proxmark3 does the emulation.
class Exporters {
  /// Flipper Zero ".nfc" file for a MIFARE Classic dump.
  static String flipperNfc(ClassicDump d) {
    final b = StringBuffer();
    b.writeln('Filetype: Flipper NFC device');
    b.writeln('Version: 4');
    b.writeln('# Generated by TagWallet (phone-read). Emulate on Flipper/Proxmark.');
    b.writeln('Device type: Mifare Classic');
    final uidBytes = _uidToSpaced(d.uid);
    b.writeln('UID: $uidBytes');
    b.writeln('ATQA: 00 04');
    b.writeln('SAK: 08');
    b.writeln('Mifare Classic type: ${d.sectorCount >= 40 ? '4K' : '1K'}');
    b.writeln('Data format version: 2');
    // Flipper expects "Block N: XX XX ..." lines, 16 bytes each.
    var blockIndex = 0;
    for (final s in d.sectors) {
      for (final blk in s.blocks) {
        final hex = blk.contains('??') ? _unknownBlock() : blk;
        b.writeln('Block $blockIndex: $hex');
        blockIndex++;
      }
    }
    // Record which sector keys were recovered, as a comment.
    for (final s in d.sectors) {
      if (s.keyUsed != null) {
        b.writeln('# Sector ${s.sector} keyA: ${s.keyUsed}');
      }
    }
    return b.toString();
  }

  /// Proxmark3 ".bin"-style hex (one block per line, no spaces) — easy to feed
  /// to `hf mf restore`/`eload` workflows after conversion.
  static String proxmarkHex(ClassicDump d) {
    final b = StringBuffer();
    for (final s in d.sectors) {
      for (final blk in s.blocks) {
        b.writeln(blk.contains('??') ? '00000000000000000000000000000000'
            : blk.replaceAll(' ', ''));
      }
    }
    return b.toString();
  }

  static Future<File> save(String filename, String contents) async {
    final dir = await getApplicationDocumentsDirectory();
    final f = File('${dir.path}/$filename');
    await f.writeAsString(contents);
    return f;
  }

  static String _uidToSpaced(String uidHex) {
    final clean = uidHex.replaceAll(' ', '');
    final pairs = <String>[];
    for (var i = 0; i + 1 < clean.length; i += 2) {
      pairs.add(clean.substring(i, i + 2).toUpperCase());
    }
    return pairs.join(' ');
  }

  static String _unknownBlock() =>
      List.filled(16, '00').join(' ');
}
